[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "easycart-rate-limiter"
version = "0.1.0"
description = "EasyCart Rate Limiter"
authors = [{ name = "Melwin" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
