name: Deploy EasyCart to Elastic Beanstalk (CD)

on:
  workflow_run:
    workflows: ["Build EasyCart (CI)"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success'
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Download CI Artifact Folder
        run: |
          mkdir -p artifact
          gh run download ${{ github.event.workflow_run.id }} \
            -n easycart-app-zip \
            --dir artifact
        env:
          GH_TOKEN: ${{ github.token }}

      - name: List artifact contents
